# Generated by Django 3.1.3 on 2020-11-06 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gazetracker',
            name='created_at',
        ),
    ]
