# Generated by Django 3.1.3 on 2020-11-06 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_gazetracker_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gazetracker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
