# Generated by Django 2.1.7 on 2019-06-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_eventtracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100)),
                ('event', models.CharField(max_length=100)),
            ],
        ),
    ]
