# Generated by Django 2.1.7 on 2019-06-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_fullscreen'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtracker',
            name='timestamp',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='fullscreen',
            name='timestamp',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AddField(
            model_name='react360',
            name='timestamp',
            field=models.TimeField(default='20:00'),
        ),
    ]
