# Generated by Django 2.1.7 on 2019-06-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190603_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtracker',
            name='timestamp',
            field=models.CharField(default='20.05.2019', max_length=100),
        ),
        migrations.AlterField(
            model_name='fullscreen',
            name='timestamp',
            field=models.CharField(default='20.05.2019', max_length=100),
        ),
        migrations.AlterField(
            model_name='react360',
            name='timestamp',
            field=models.CharField(default='20.05.2019', max_length=100),
        ),
    ]
