# Generated by Django 3.1.1 on 2020-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazetracker',
            name='gaze_direction_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gazetracker',
            name='gaze_direction_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gazetracker',
            name='gaze_direction_z',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gazetracker',
            name='gaze_origin_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gazetracker',
            name='gaze_origin_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gazetracker',
            name='gaze_origin_z',
            field=models.FloatField(),
        ),
    ]
