# Generated by Django 3.1.1 on 2020-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201118_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazetracker',
            name='gaze_point_x',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gazetracker',
            name='gaze_point_y',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gazetracker',
            name='gaze_point_z',
            field=models.FloatField(),
        ),
    ]
