# Generated by Django 3.1.1 on 2020-11-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201118_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vertices_x', models.CharField(max_length=100)),
                ('vertices_y', models.CharField(max_length=100)),
                ('vertices_z', models.CharField(max_length=100)),
            ],
        ),
    ]
